"""add vm_state field to Instance

Revision ID: 345ce631ffcd
Revises: f9c112da559
Create Date: 2013-09-26 18:52:28.429066

"""

# revision identifiers, used by Alembic.
revision = '345ce631ffcd'
down_revision = 'f9c112da559'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('vm_state', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'vm_state')
    ### end Alembic commands ###
