"""Initial structure

Revision ID: f9c112da559
Revises: None
Create Date: 2013-09-26 03:55:37.436797

"""

# revision identifiers, used by Alembic.
revision = 'f9c112da559'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('power_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ipaddr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=15), nullable=True),
    sa.Column('assigned_vm_id', sa.Integer(), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.ForeignKeyConstraint(['assigned_vm_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipaddr')
    op.drop_table('instances')
    ### end Alembic commands ###
